### ISSUE TITLE
在gradle里，修改targetSDK的值，不然文件读写权限拿不到

### ISSUE THREAD

**Issue by YifengLyu0502** [hmlmmy/COMP5216Hiking#11]

**Comment by hmlmmy** [comment]
defaultConfig {
        applicationId "comp5216.sydney.edu.au.hiketogether"
        minSdk 24
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

**Comment by hmlmmy** [comment]
targetSdk改成31

**Comment by hmlmmy** [comment]
所有人直接拉取新的fix_main，这个sdk改过了
